### ISSUE TITLE
unable to parse html page given selectors

### ISSUE THREAD

**Issue by pgoldweic** [html-to-text/node-html-to-text#288]
I am trying to parse HTML pages which belong to the public Canvas LMS guides. Whenever I try something like the following:

        const { convert } = require('html-to-text')
	let simpleSelectors = ['h1.PageTitle']
	let selectorSpecs = [{ selector: 'h1.PageTitle', format: 'heading', options: { uppercase: false}}]
        let text = convert(html, {baseElements: { selectors: simpleSelectors }, selectors: selectorSpecs})

I am getting the following error:

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError: str.replace is not a function
    at prettyPrintPosition (D:\eclipse-projects\myproject\node_modules\parseley\lib\parseley.cjs:151:19)
    at parse_ (D:\eclipse-projects\myproject\node_modules\parseley\lib\parseley.cjs:137:13)
    at Object.parse1 (D:\eclipse-projects\myproject\node_modules\parseley\lib\parseley.cjs:157:12)
    at toAstTerminalPairs (D:\eclipse-projects\myprojec\tnode_modules\selderee\lib\selderee.cjs:92:52)
    at new DecisionTree (D:\eclipse-projects\myproject\node_modules\selderee\lib\selderee.cjs:81:31)
    at compile$1 (D:\eclipse-projects\myproject\node_modules\html-to-text\lib\html-to-text.cjs:1125:31)
    at compile (D:\eclipse-projects\myproject\node_modules\html-to-text\lib\html-to-text.cjs:2045:10)
    at convert (D:\eclipse-projects\myproject\node_modules\html-to-text\lib\html-to-text.cjs:2065:10)
    at retrieveTextFromHTML (D:\eclipse-projects\myproject\retrieveSitesText.js:61:15)
    at retrievePageTitlePlusText (D:\eclipse-projects\myproject\retrieveSitesText.js:255:14)

I can't tell whether there's a bug or I'm doing something wrong (apparently code like this which I wrote a couple of months ago was working, but I can't reproduce that successful behavior now)

**Comment by KillyMXI** [comment]
It would've been more helpful if you followed the Bug Report template. (Opening an underprepared issue is inconsiderate to maintainers because it requires more effort to decipher.)

I've no idea what is "the public Canvas LMS guides", but it most likely doesn't matter here.

If the code was working before and doesn't work now - one of obvious things to check - package versions used now and then.

I see you trying to do something possibly not intended, by providing very narrow selectors for baseElements, as if the page title is the only thing, you're interested in. In that case you might not need `html-to-text`...

I can't reproduce the issue on the latest version with just the options provided.

```js
const html = '<h1 class="PageTitle">Pick me</h1><div>ignore me</div>';
const simpleSelectors = ['h1.PageTitle'];
const selectorSpecs = [{ selector: 'h1.PageTitle', format: 'heading', options: { uppercase: false } }];
const text = convert(
  html,
  { baseElements: { selectors: simpleSelectors }, selectors: selectorSpecs }
);
console.log(text);
```
\- this just works and outputs `Pick me`.

Stack trace gives me an idea what to fix in upstream package to prevent an error in error reporting, but not the actual cause.

Error in the stack trace most likely happened *not* with the options provided.

You have to put more effort on your side and make sure you are running what you think you are running.

**Comment by KillyMXI** [comment]
I was able to reproduce the error by passing an object instead of a string where selector string is expected.

Check the actual config you're passing.
